SELECT * FROM BOARD;

INSERT INTO BOARD(TITLE,CONTENTS)
VALUES ('test22','1212');
INSERT INTO BOARD
VALUES(NULL,'안녕?','하세요','hong',NOW());


SELECT * FROM BOARD;

SELECT TITLE,CONTETNTS,IFNULL(USERID, 'ABCD')as id
FROM BOARD;
UPDATE BOARD
SET
	CDATETIME=NOW()
WHERE BOARDENO <=2;


SELECT TITLE,
DATE_FORMAT(CDATETIME,'%Y-%m-%d %H:%i:%s')
FROM BOARD;



INSERT INTO COMMENT
VALUES(NULL,'JAVA!SCRIPT','test1',NOW());

SELECT * FROM COMMENT;
SELECT * FROM BOARD;

SELECT * 
FROM BOARD B
INNER JOIN CONTETNT C ON B.BOARDNO=C.BOARDNO;




