CREATE TABLE EMP_LOG(
    L_EMPNO NUMBER,
    L_MGR NUMBER,
    O_SAL NUMBER,
    N_SAL NUMBER,
    L_COMM NUMBER,
    L_ID VARCHAR2(30),
    EVENT VARCHAR2(20),
    L_TIME DATE
);
COMMIT;

CREATE OR REPLACE TRIGGER EMP_TRIGGER
    AFTER
    INSERT OR UPDATE OR DELETE ON EMP
    FOR EACH ROW
    
    BEGIN
    IF INSERTING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO,:NEW.MGR,:NEW.SAL,:NEW.COMM,SYS_CONTEXT('USERNV','SESSION_USER'),'I',SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO EMP_LOG
            VALUES(:NEW.EMPNO,:NEW.MGR,:NEW.SAL,:NEW.COMM,SYS_CONTEXT('USERNV','SESSION_USER'),'U',SYSDATE );

    ELSIF DELETING THEN
            RAISE_APPLICATION_ERROR(-20003,'사원데이터는 삭제할수 없습니다.');
            --VALUES(:OLD.EMPNO,:OLD.MGR,:OLD.SAL,:OLD.COMM,SYS_CONTEXT('USERNV','SESSION_USER'),'D',SYSDATE );

    
    END IF;
    END;
    /
    SELECT SYS_CONTEXT('USERNV','SESSION_USER')
    FROM DUAL;
    
    
    SELECT * FROM EMP;
    SELECT * FROM EMP_LOG;
    UPDATE EMP
    SET
        SAL=2050
    WHERE EMPNO='7521';
    COMMIT;
    
    
    INSERT INTO EMP(EMPNO, ENAME, SAL)
    VALUES('1234','HONG',9999);
    
    
    INSERT INTO EMP(EMPNO, ENAME, SAL)
    VALUES('1234','KIM',3000,-300);
    
    INSERT INTO EMP(EMPNO, ENAME, SAL)
    VALUES('1122','ABCD',2500);
    
  --  ENROL 테이블 트리거 만들기

--조건 1. 테이블명은 ENROL_LOG
     --  컬럼은 과목번호, 학생번호, 수정전시험점수, 수정후시험점수, 작업자ID, 작업종류, 작업날짜
--조건 2. INSERT할 경우 ENROL_LOG에 해당 내용 자동 저장
       단, 시험점수가 0~100사이가 아니면 0으로 저장
--조건 3. UPDATE할 경우 ENROL_LOG에 해당 내용 자동 저장
       단, 시험점수가 0~100사이가 아니면 에러를 띄운 후 종료
--조건 4. DELETE할 경우 에러를 띄운 후 종료
​       DESC ENROL
    CREATE TABLE ENROL_LOG(
    L_SUBNO CHAR(3)
    L_STUNO CHAR(8)
    O_ENRGRADE NUMBER;
    N_ENRGRADE NUMBER;
    L_ID CHAR(20);
    EVENT CHAR(1),
    L_TIME DATE
);
COMMIT;
    
    SELECT * FROM ENROL;
    
    
   CREATE OR REPLACE TRIGGER ENROL_TRIGGER
    AFTER -- 트리거실행 시점(BEFORE OF AFTER
    INSERT OR  UPDATE OR DELECT ON ENROL--EMP테이블에 레코드가INSERT 혹은 UPDATE될때 실행
    FOR EACH ROW  
    BEGIN
    IF INSERTING THEN
        IF :NEW.ENR_GRADE < 0 OR :NEW.ENR_GRADE > 100 THEN
            :NEW.ENR_GRADE := 0;
        END IF;
        INSERT INTO ENROL_LOG
        VALUES(:NEW.SUB_NO, :NEW.STU_NO, :NEW.ENR_GRADE, :NEW.ENR_GRADE, SYS_CONTEXT('USERENV','SESSION_USER'), 'I', SYSDATE);
    ELSIF UPDATING THEN
        IF :NEW.ENR_GRADE < 0 OR :NEW.ENR_GRADE > 100 THEN
            RAISE_APPLICATION_ERROR(-20004, '점수는 0~100사이');
        END IF;
        INSERT INTO ENROL_LOG
        VALUES(:NEW.SUB_NO, :NEW.STU_NO, :OLD.ENR_GRADE, :NEW.ENR_GRADE, SYS_CONTEXT('USERENV','SESSION_USER'), 'U', SYSDATE);
    ELSIF DELETING THEN
        RAISE_APPLICATION_ERROR(-20005, '삭제 불가!');
    END IF;
END;
/
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM ENROL_LOG;
INSERT INTO ENROL
VALUES('101', '20142021', 200);
COMMIT;

UPDATE ENROL
SET
    ENR_GRADE = 91
WHERE STU_NO = '20142021';


