--
SELECT DECODE(SUBSTR(JUMIN,7,1),1,'남자','여자')
FROM STU;

SELECT SYSDATE --날짜출력
FROM STU;

INSERT INTO BOARD
VALUES(1,'오라클 재밋다','뻥인데',SYSDATE,SYSDATE);
COMMIT;

SELECT TO_CHAR(CDATETIME, 'YYYY.MM.DD HH24:MI')
FROM BOARD;

SELECT MAX(STU_HEIGHT) --STUDENT테이블에서 키가 가장큰사람을 찾음
FROM STUDENT;


SELECT AVG(SAL) --EMP테이블에서 평균급여를 구함
FROM EMP;

SELECT MAX(SAL) --EMP에서 가장많은 급여를 구함
FROM EMP;

SELECT* --DB에서 가장많은 급여를 받는사람을 구함
FROM EMP
WHERE SAL = (
SELECT MAX(SAL)
FROM EMP
);


SELECT JOB,ROUND(AVG(SAL),2) --급여가 1500이상인 직급의 평균급여를 구함
FROM EMP
WHERE SAL>=1500
GROUP BY JOB
HAVING AVG(SAL)>=2500; --평균값을 구하고 평균급여가 2500인 부서만 표현


SELECT *
FROM STUDENT;

SELECT *
FROM ENROL;

SELECT STU_NO,STU_NAME,AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S.STU_NO,STU_NAME;


SELECT STU_NO,STU_NAME,AVG(ENR_GRADE) AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S.STU_NO;


SELECT 
FROM STUDENT S
INNER JOIN(
SELECT S.STU_NO,AVG(ENR_GRADE) AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S.STU_NO

)T ON S.STU_NO =T.STUNO;



SELECT S.*,ENR_GRADE 
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO;


SELECT E1.*, E2.ENAME 매니저이름
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR=E2.EMPNO;

SELECT *
FROM DEPARTMENT;



SELECT *
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 =D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART=D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART=D3.DEPTNO
WHERE NAME='서진수';

SELECT *
FROM EMP E
INNER JOIN SALGRADE ON E.SAL BETWEEN LOSAL AND HISAL;


SELECT * FROM STUDENT;

SELECT * FROM ENROL;


SELECT  S.STU_NO,STU_NAME,STU_DEPT,ENR_GRADE,SUB_NAME
FROM STUDENT  S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO=SUB.SUB_NO;
GROUP BY S.STU_NO;


SELECT STU_DEPT,AVG(ENR_GRADE) 
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY STU_DEPT;


SELECT S.STU_NO,STU_NAME,AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
INNER JOIN(
SELECT STU_DEPT,AVG(ENR_GRADE) AVG_DEPT
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY STU_DEPT

) T ON S.STUDEPT=T.STU_DEPT;
GROUP BY S. STUNO,STU_NAME,AVG_DEPT
HAVVING AVG (ENR_GRADE>AVG_DEPT;





SELECT S.STU_NO,STU_NAME,COUNT(*)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S. STUNO,STU_NAME
HAVING COUNT(*) >=2;



