--프로시저
CREATE OR REPLACE PROCEDURE TEST_PROC
IS 
BEGIN
        DBMS_OUTPUT.PUT_LINE('hellooracle');
    END;
    /
    
SET SERVEROUTPUT ON;

SET SERVEROUTPUT ON;
EXEC TEST_PROC;


CREATE OR REPLACE PROCEDURE EMPINFO_PROC(I_EMPNO IN NUMBER)
IS
    O_ENAME

BEGIN 
SELECT ENAME,SAL
INTO O_ENAME,O_SAL
FROM EMP
WHERE EMPNO=I_DEPTNO;

DBMS_OUTPUT.PUT_LINE(O_ENAME||'님의 급여는 '||O_SAL||'입니다.');
END;
/
SELECT * FROM EMP;
EXEC EMPINFO_PROC(7654);

EXEC EMPSAL_PROC(7654,300)

CREATE OR REPLACE PROCEDURE EMPSAL_PROC(
    I_EMPNO IN EMP.EMPNO%TYPE,
    I_SAL IN EMP.SAL%TYPE
)
IS 
    O_COUNT NUMBER;
BEGIN
UPDATE EMP
SET 
    SAL =SAL+I_SAL
WHERE EMPNO=I_EMPNO;
O_COUNT :=SQL%ROWCOUNT;
COMMIT;
IF O_COUNT = 0 THEN
    DBMS_OUTPUT.PUT_LINE('사번읋 확인해주세요');
ELSIF O_COUNT =1 THEN
    DBMS_OUTPUT.PUT_LINE('수정되었습니다');
ELSE 
    DBMS_OUTPUT.PUT_LINE('2개이상의 데이터가 저장됨');
END IF;
END;
/
SET SERVEROUTPUT ON;
SELECT * FROM EMP;
EXEC EMPSAL_PROC(7644,100);

SELECT * FROM ENROL;
--프로시저 호출
--ENROL_PROC('학번','과목번호','수정할점수')
--점수가 0미만 100초과이면 점수의 범위는 1~100입니다 출력
--학번 과목번호에 해당하는 점수는  3번째 인자값으로변경
CREATE OR REPLACE PROCEDURE ENROL_PROC(
    I_STUNO IN ENROL.STU_NO%TYPE,
    I_SUBNO IN ENROL.SUB_NO%TYPE
    )
    IS 
        O_COUNT NUMBER;
    BEGIN
    UPDATE ENROL
    SET 
     ENR_GRADE =ENR_GRADE+I_ENR_GRADE
    WHERE STU_NO=I_STU_NO;
    O_COUNT :=SQL%ROWCOUNT;
    COMMIT;
     IF O_COUNT = 0 THEN
        DBMS_OUTPUT.PUT_LINE('정보를 다시확인해주세요');
    ELSIF O_COUNT<0 AND OCOUNT>100 THEN
        DBMS_OUTPUT.PUT_LINE('점수의범위는 1~100입니다');
    ELSIF O_COUNT =1 THEN
     DBMS_OUTPUT.PUT_LINE('수정되었습니다');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('2개이상의 데이터가 저장됨');
    END IF;
    END;
    /
    SET SERVEROUTPUT ON;
    SELECT * FROM ENROL;
    EXEC ENROL_PROC(20131001,101);
    
    