
--PL/SQL
--사용자정의 함수,프로시저,트리거
--PL/SQL
-- 선언부(선택),실행부,에외처리(선택)
--마지막을 '/'로마무리

--숫자를 2배로 돌려주는 함수생성

LENGTH();
--숫자를 2배로 돌려주는 함수생성

CREATE OR REPLACE FUNCTION MULTI(I_VALUE,NUMBER)
RETURN NUMBER
IS
--변수선언
BEGIN
--실행부
    Return I_VALUE *2;
END;
/


SELECT * ENR_GRADE,
FROM ENROL;

--DATA_FUNC 이름의 함수를 생성
--
CREATE OR REPLACE FUNCTION DATE_FUNC(I_DATE DATE)
RETURN VARCHAR2 
IS

BEGIN
RETURN TO_CHAR(I_DATE,'YYYY/MM/DD HH24:MI:SS');

END:
/

SELECT 
B.*,
DATE_FUNC(CDATEIME)
FROM TBL_BOARD B;



CREATE OR REPLACE FUNCTION DATE_FUNC2(I_DATE IN DATE,I_KEY IN VARCHAR2)
RETURN VARCHAR2

IS 
    O_DATE VARCHAR2(100);
BEGIN
    IF I_KEY='DATETIME'THEN
    O_DATE := TO_CHAR(I,DATE,'YYYY-MM-DD HH24:MI:SS')'
    ELSIF I_KEY='DATE' THEN 
     O_DATE := TO_CHAR(I,DATE,'YYYY-MM-DD');
     ELSIF I_KEY='TIME'THEN
     O_DATE :=TO_CHAR(I_DATE,'HH24:MI:SS');
     ELSE
     O_DATE:='값 잘못입력했음ㅋ*;
     
    
END;
/


SELECT 
    DATE_FUNC2(CDATETIME,'DATETIME')||'',
    DATE_FUNC2(COATETIME,'DATE')||'',
    DATE_FUNC2(COATETIME,'TIME')
    FROM TBL_BOARD;








--GRADE_FUNC
--GRADE_FUNC(ENR_GRADE)
--ENR_GRADE값이 90이상이면 'A'리턴

CREATE OR REPLACE FUNCTION GRADE_FUNC(I_SCORE IN NUMBER)
RETURN VARCHAR2
IS

BEGIN
    IF(I_SCORE>1OO  OR I_SCORE <0 THEN
    RETURN '다시입력';
   ELSE IF(I_SCORE>=90 THEN
   RETURN 'A';
   ELSE IF(I_SCORE>=80 THEN
   RETURN 'B';
   ELSE IF(I_SCORE>=70 THEN
   RETURN 'C';
   ELSE IF(I_SCORE>=60 THEN
   RETURN 'D';
   ELSE 
   RETURN 'F';
   
   
   END IF; 
END;
/




SELECT ENR_GRADE, GRADE_FUNC(ENR_GRADE)
FROM ENROL;



--GENDER_FUNC(JUMIN)
--7번째 숫자가 1,3이면 '남자'리턴
--2,4 면 '여자'리턴
--인자값이 13자리면  '제대로 값입력하셈'리턴
CREATE OR REPLACE FUNCTION GENDER_FUNC(I_JUMIN IN NUMBER)

IF(I_JUMIN(SUBSTR(7)= 1,3) THEN
RETURN '남자';
ELSEIF (I_JUMIN(





SELECT * 
FROM STUDENT 
WHERE STU_GENDER !='M';





