SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

--학번,이름,학과,점수,과목명
CREATE OR REPLACE VIEW STUDENT_VIEW AS --OR REPLACE를 사용하면 지금내용으로대체한다
SELECT STU_NO,STU_NAME,STU_DEPT
FROM STUDENT
WHERE STU_DEPT='기계';



SELECT * FROM STUDENT_VIEW;


SELECT *
FROM EMP;

CREATE OR REPLACE VIEW EMP_VIEW AS
SELECT EMPNO,ENAME,HIREDATE
FROM EMP;

SELECT *
FROM EMP_VIEW;

UPDATE EMP_VIEW SET
ENAME=ENAME|| 


CREATE OR REPLACE VIEW STUDENT_VIEW AS
SELECT S.STU_NO,S.STU_NAME,S.STU_DEPT,AVG(ENR_GRADE) AS AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S.STU_NO,S.STU_NAME,S.STU_DEPT
WITH READ ONLY;



--VIEW에서 수정가능한경우
--하나의테이블만 참조(조인없을때)
--2.GROUP함수 없을때
--3.DISTNCT가없을때
--4. ** 읽기저뇽 옵션이없을때**
-- -->VIEW를만들때에는 읽기전용옵션을 붙여주는게좋다