SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM  ORDERS;




SELECT
    BOOKNAME,PUBLISHER
    FROM BOOK
    WHERE PRICE>=10000;
    
    
    SELECT
    BOOKNAME,PUBLISHER
    FROM BOOK
    WHERE PUBLISHER='굿스포츠'
    ORDER BY BOOKNAME;
    
    
    
    --날짜별수익
    SELECT 날짜,SUM_PRICE
    FROM(
    SELECT TO_CHAR(ORDERDATE,'YYYY/MM/DD')AS 날짜,SUM(SALEPRICE)
    AS SUM_PRICE,1 AS ORDERKEY
FROM ORDERS
GROUP BY ORDERDATE
UNION
SELECT '매출총액' AS 날짜,
SUM(SALEPRICE) AS SUM_PRICE,
2 AS ORDERKEY
FROM ORDERS
)
ORDER BY ORDERKEY, SUM_PRICE DESC;



책가격이 가장 높은 상위 3개의 책이름 ,가격 출력

SELECT BOOKNAME,PRICE
FROM(
SELECT *
FROM BOOK
ORDER BY PRICE DESC
)B
 WHERE ROWNUM<=3;   
    
    
    
    
SELECT * FROM BOOK
WHERE BOOKNAME LIKE '%축구%'; --%는 앞뒤에 무엇이 있어도 상관없음

--CASE~WHEN
--날짜별 매출
--날짜,해당의 매출,매출이 20000이상일경우 '상',10000이상일 경우'중',그외는 '하'로표기


SELECT *
ORDER DATE 
SUM(SALEPRICE)
FROM ORDERS;
CASE 
WHEN  SUM (SALPRICE)=>20000THEN'상'
WHEN  SUM (SALPRICE)=>10000THEN'중'
ELSE '하'
END 상중하
FROM ORDERS 
GROUP BY ORDERDATE;








    