SELECT * FROM BOOK;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;



--1.구매자이름,책이름,구매일출력
SELECT  NAME,BOOKNAME,ORDERDATE
FROM CUSTOMER C
INNER JOIN ORDERS O ON B.CUSTID=O.CUSTID
INNER JOIN BOOK B ON B.BOOKID=O.BOOKID;

