--EMP
--1,내부서의 평균급여보다 많은 급여를 받는사람 출력


SELECT *
FROM EMP E
INNER JOIN(
SELECT DEPTNO,AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY DEPTNO
)T ON E.DEPTNO=T.DEPTNO
WHERE SAL>AVG_SAL;

SELECT DEPTNO,AVG(SAL)
FROM EMP
GROUP BY DEPTNO;


SELECT DEPTNO, AVG(SAL)
FROM EMP;

--4.본인 학과의 시험평균점수보다 높은 시험점수를 가진 학생이 학번,이름,평균점수
SELECT S.STU_NO,STU_NAME.ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU__NO=E.STU_NO
INNER JOIN(
SELECT AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU__NO=E.STU_NO
GROUP BY STU_DEPT
)T ON S.STU_DEPT=T.STU_DEPT
GROUP BY S.STU_NO,STU_NAME,AVG_GRADE
HAVING AVG(ENR_GRADE)> AVG_GRADE;

SELECT * FROM TBL_USER;
SELECT * FROM BOARD;
SELECT * FROM TBL_COMMENT;

--사용자 게시글 조회수를 총합이
--모든게시글 조회수 전체 평균보다 높은 게시글의 작성자 ID,이름,조회수총합출력
--작성자 아이디,이름,조회수 총합출력

SELECT B.USERID,U.USERNAME,SUM(CNT)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON  B.USERID=U.USERID
GROUP BY B.USERID,U.USERNAME
HAVING SUM(CNT)>(
SELECT AVG(CNT)
FROM TBL_BOARD
);



