--UNION,UNION ALL
--SUBJECT 쿼리 실행결과를 합쳐주는 명령어

SELECT
STU_NO,
STU_NAME,
STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT>=170
UNION --중복없이 하나로 합쳐서 출력됨
--UNIONALL:중복된값도표현
SELECT
STU_NO,
STU_NAME,
STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT>=60;

--주의점
--1.컬럼의개수와 타입이 같아야한다
--2. 컬럼의 이름(별칭)은 먼저나오는 쿼리를 따른다
--3.정렬(ORDER BY)는 맨 마지막 줄에 작성.첫번재 쿼리 컬럼을 기준으로 쓴다


SELECT STU_NAME FROM STUDENT
UNION
SELECT COUNT(*)FROM STUDENT;--컬럼의 데이터 타입이 달라서 오류발생

SELECT STU_NAME AS ZZZ FROM STUDENT
UNION
SELECT STU_DEPT FROM STUDENT;--컬럼의 이름은 첫번째 쿼리를 따른다

SELECT STU_DEPT ,COUNT(*)학생수
FROM STUDENT
GROUP BY STU_DEPT
UNION
SELECT '전체 학생수',COUNT(*)
FROM STUDENT;

SELECT * FROM STUDENT;

SELECT STUNO,STU_NAME,AVG(ENR_GRADE) AS AVG_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY STU_NO,STU_NAME
UNION
SELECT '전체평균점수',AVG(ENR_GRADE),
2 AS 1 ORDERKEY
FROM ENROL

ORDER BY ORDERBYKEY,AVG_GRADE
;

SELECT 
STU _NAME,STU_DEPT,STU_HEIGHT
FROM STUDENT;



SELECT *
FROM(
    SELECT
    STUNAME,STU_DEPT,STU_HEIGT
    FROM STUDENT
    );

SELECT STUNAME,AVG_GRADE
FROM(
SELECT STUNO,STU_NAME,AVG(ENR_GRADE) AS AVG_GRADE
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY STU_NO,STU_NAME
UNION
SELECT '전체평균점수',AVG(ENR_GRADE),
2 AS 1 ORDERKEY
FROM ENROL

ORDER BY ORDERBYKEY,AVG_GRADE
;
SELECT
STU_NO,
STU_NAME,
STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT>=60;
