SELECT 
    STU_DEPT,
    COUNT(*)NUM
COUNT(*)
FROM STUDENT;
GROUP BY STU_DEPT;

SELECT JOB,AVG(SAL)
FROM EMP
GROUP BY JOB;

--학번,이름,시험점수
SELECT * STU_NO,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STY_NO=E.STU_NO;

--학번,이름,급여,등급
SELECT * EMPNO,ENAME,SAL,GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;



--학번,이름,시험점수
SELECT S.STU_NO,STU_NAME,AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S.STU_NO, STU_NAME;



SELECT E1.EMPNO,E1.ENAME,E2.ENAME AS MANAGER
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR=E2.EMPNO;



SELECT PROFNO,NAME,D1.DNAME,D2.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON D1.DEPTNO=D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART=D2.DEPTNO;


SELECT PROFNO,NAME,D1.DNAME,D2.DNAME,D3.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO=D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART=D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART=D3.DEPTNO;


--STUDENT, ENROL, SUBJECT
--PROFESSOR,STU,DEPARTMENT
--EMP,DEPT,SALGRADE


SELECT * FROM EMP;
SELECT * FROM STUDENT;

SELECT S.STU_NO,STU_NAME,ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO=SUB.SUB_NO
WHERE SUB_NAME='컴퓨터개론';

SELECT STU_NO,STU_NAME, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S.STU_NO,STU_NAME
HAVING AVG(ENR_GRADE)>=70;


SELECT STU_NO,STU_NAME, COUNT(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO=E.STU_NO
GROUP BY S.STU_NO,STU_NAME
HAVING COUNT(*)>=2;


SELECT DNAME,ROUND(AVG(S.GRADE),0)
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO
GROUP BY DNAME;

SELECT DNAME,AVG(SAL) AS SAL_AVG
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO
GROUP BY DNAME;


SELECT E1.EMPNO,E1.ENAME
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR=E2.EMPNO
WHERE E2.ENAME='BLAKE';

SELECT * FROM STU;
SELECT * FROM DEPT;
SELECT * FROM PROFESSOR;

--PROFESSOR,STU,DEPARTMENT
SELECT COUNT(*)
FROM STU S
INNER JOIN DEPARTMENT D1  ON S.DEPTNO1=D1.DEPTNO --학생이 어떤학과인지 찾음
INNER JOIN DEPARTMENT D2  ON D1.PART=D2.DEPTNO --
INNER JOIN DEPARTMENT D3 ON D2.PART=D3.DEPTNO
WHERE D3.DNAME='공과대학';


--서브쿼리
--STUDENT 테이블에서 학과별 평균키

SELECT * FROM DEPT;
SELECT * FROM EMP;
--1.학과,학번,이름,키,내가속한 학과의 평균키

SELECT STU_NO,STU_NAME,S.STU_DEPT,STU_HEIGHT,AVG_DEPT
FROM STUDENT S
INNER JOIN (
SELECT STU_DEPT,AVG(STU_HEIGHT) AVG_DEPT
FROM STUDENT
GROUP BY STU_DEPT
)T ON S.STU_DEPT=T.STU_DEPT
WHERE STU_HEIGHT>AVG_DEPT;


SELECT EMPNO,ENAME,SAL,ENAME,ROUND(AVG_DEPT,1)
FROM EMP E
INNER JOIN(
SELECT DEPTNO,DNAME,AVG(SAL) AVG_DEPT
FROM EMP E
GROUP BY DEPTNO
)T ON E.DEPTNO=T.DEPTNO
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO
WHERE SAL > AVG_DEPT;

SELECT * FROM PROFESSOR;


SELECT PROFID,PROF_NO,POSITION,MAX(PAY)
FROM PROFESSOR P
INNER JOIN (
SELECT POSITION,MAX(PAY) AS MAX_PAY
FROM PROFESSOR
GROUP BY POSITION
)T ON P.POSITION=T.POSITION AND P.PAY=T.MAX_PAY;



SELECT NAME,D2.DNAME,AVG(PAY)
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO=D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART=D2.DEPTNO
INNER JOIN(
SELECT D2.DNAME,AVG(PAY) AS AVG_PAY
FROM PROFSSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO=D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART=D2.DEPTNO
GROUP BY D2.DNAME
)T ON D2.DNAME=T.DNAME
WHERE PAY>AVG_PAY;

--각 직급(POSITION)별 가장 많은 급여를 받는사람의
--교수번호,이름,급여 출력
--본인학부의 평균급여보다 높은 급여를 받는 교수의 교수번호,이름,급여 출력

SELECT * FROM EMP;

SELECT *
FROM EMP E
INNER JOIN (
SELECT DEPTNO,MAX(SAL) AS MAX_SAL
FROM EMP 
GROUP BY DEPTNO
)T ON E.DEPTNO=T.DEPTNO AND E.SAL=T.MAX_SAL;


SELECT *
FROM STUDENT S
INNER JOIN(
SELECT  STU_DEPT,MAX(STU_HEIGHT) AS MAX_HEIGHT
FROM STUDENT 
GROUP BY STU_DEPT
)T
 ON S.STU_DEPT=T.STU_DEPT AND S.STU_HEIGHT=T.MAX_HEIGHT;





SELECT SUBSTR(STUNO,1,2), AVG(HEIGHT) 
FROM STU
GROUP BY SUBSTR(STUNO,1,2);

-- 남자와 여자의 평균키 출력
SELECT SUBSTR(JUMIN,7,1),AVG(HEIGHT)
FROM STU
GROUP BY SUBSTR(JUMIN,7,1);

SELECT * FROM PROFESSOR;
SELECT * FROM STU;


SELECT P.NAME,P.POSITION,NAL('담당학생없음')
FROM PROFESSOR P
LEFT JOIN STU S ON P.PROFNO=S.PROFNO;


SELECT STUNO,S.NAME,P.NAME
FROM STUDENT S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO;

--점수없으면 '점수없음'
SELECT STU_NAME, NVL(TO_CHAR(AVG(ENR_GRADE)),'점수없음')
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;

SELECT * FROM EMP;
--EMP 
--부하직원의 수를 구하고싶다
--없으면 0으로 출력


SELECT EMPNO,ENAME,NVL(CNT,0)AS CNT
FROM EMP E
LEFT JOIN(
SELECT MGR,COUNT(*) AS CNT
FROM EMP E
WHERE MGR IS NOT NULL
GROUP BY MGR
)T ON T.MGR = E.EMPNO
ORDER BY CNT DESC;

---
    SELECT 
    EMAIL,
     RPAD('*', INSTR(EMAIL,'@')-1, '*')
     RPAD('*',INSTR(EMAIL,'.')-INSTR(EMAIL,'@')-1,'*')
      SUBSTR(EMAIL, INSTR(EMAIL,'.')) AS 메일
    FROM PROFESSOR;


